hyper_params:
  colsample_bynode: 0.8
  max_depth: 5
  subsample: 0.8
  n_estimators: 500
  learning_rate: 1
  gamma: 3
  min_child_weight: 9
  objective: binary:logistic
  metric: error
  reg_alpha: 3.5
  nthread: 4
